language: php
env:
  - TWIG_VERSION="^1.0"
  - TWIG_VERSION="^2.0"
  - TWIG_VERSION="^3.0"
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
jobs:
  exclude:
    - php: 7.0
      env: TWIG_VERSION="^3.0"
    - php: 7.1
      env: TWIG_VERSION="^3.0"
before_install:
    - composer require twig/twig:${TWIG_VERSION}
install:
    - composer --prefer-source -n install
